Replace deprecated slash for division
AgePartnership/oleg-starter-pack pull request #27
Opened 2021-10-12 12:55 UTC by kimoshinowo98

Ticket: https://webjobs.agepartnership.co.uk/desk/tickets/5687300/messages

Changes:
- Use sass-migrator to change division slashes to multiplications or to use math.div()

Checks:
- Non-malicious
- Sense

2024-01-10 16:27 UTC, ryanfitton-ap commented on base/_grid.scss
>  // Example use: @include grid-cell(2,2,1,1)
We may need to add `@use 'sass:list';` to the top of the file, unless this is already added by Gulp when we compile?

I have tested with a test file: `test.scss`:
```
@use 'sass:list';

@mixin grid-cell($col-start, $col-end, $row-start, $row-end) {
    -ms-grid-column: $col-start;
    grid-column: list.slash($col-start, $col-end);
    -ms-grid-column-span: $col-end - $col-start;
    -ms-grid-row: $row-start;
    grid-row: list.slash($row-start, $row-end);
    -ms-grid-row-span: $row-end - $row-start;
}

.test {
    @include grid-cell(2, 2, 1, 1)
}
```

And running:  `sass test.scss test.css`, i'm running Sass `1.57.1 compiled with dart2js 2.18.6`

2024-01-10 16:28 UTC, ryanfitton-ap requested changes
We may need to add `@use 'sass:list';` to the top of the file, unless this is already added by Gulp when we compile?

I have tested with a test file: `test.scss`:
```
@use 'sass:list';

@mixin grid-cell($col-start, $col-end, $row-start, $row-end) {
    -ms-grid-column: $col-start;
    grid-column: list.slash($col-start, $col-end);
    -ms-grid-column-span: $col-end - $col-start;
    -ms-grid-row: $row-start;
    grid-row: list.slash($row-start, $row-end);
    -ms-grid-row-span: $row-end - $row-start;
}

.test {
    @include grid-cell(2, 2, 1, 1)
}
```

And running:  `sass test.scss test.css`, i'm running Sass `1.57.1 compiled with dart2js 2.18.6`

2024-01-10 16:30 UTC, ryanfitton-ap commented
Like you have done in this other PR https://github.com/AgePartnership/web.agepartnership.co.uk/blob/642991ac3006cfaa75e002236ee3ddafbb87298e/resources/css/landing/equity-release/202206-search-journey/_content-highlight-banner.scss with `@use 'sass:math';`

2024-01-11 14:13 UTC, kimoshinowo98 commented
Tested on https://github.com/AgePartnership/web.agepartnership.co.uk/pull/3353 and seems to work

2024-01-15 10:44 UTC, ryanfitton-ap approved these changes
If working happy to improve. If we see any issues in the future can be referred back to this PR noting the fix is to add `@use 'sass:list';`

2024-01-16 15:06 UTC, beccadawson commented
> If working happy to approve. If we see any issues in the future can be referred back to this PR noting the fix is to add `@use 'sass:list';`

Am confused, we have this in the file already?

2024-01-18 11:42 UTC, merged