Feature/remove mixins to starter pack
AgePartnership/oleg-starter-pack pull request #35
Opened 2023-03-17 13:28 UTC by ryanfitton-ap

Remove mixins and place in Starter Pack

Ticket: https://webjobs.agepartnership.co.uk/app/tasks/15034642

Related component library PR: 

Checks:

- Sanity
- Review
- Malice

2023-04-13 10:54 UTC, kimoshinowo98 requested changes
Just one thing. I'm also not sure about whether it's ok for the lockfileVersion in package-lock.json to be updated - @beccadawson do you know if that's ok?

2023-04-13 11:01 UTC, beccadawson requested changes

2023-04-13 18:54 UTC, ryanfitton-ap commented on base/_mixins.scss
> +        @include icon-setup('left', 'x', 0); //Icon positioned Left, animate on X axis, 0px margin for between text and icon
Updated

2023-04-17 14:21 UTC, beccadawson commented on package-lock.json
Thought so, we didn't get round to adding automatic switching stuff everywhere

Running `nvm use` should switch you onto the right versions

2023-04-18 12:29 UTC, ryanfitton-ap commented on package-lock.json
@beccadawson 

Okay, tried these:


```
nvm use lts/erbium

nvm version

* States: v12.22.12

npm cache clear --force

* Deleted the node modules folder too

npm install
```

But no new changes have been tracked in the lockfile

2023-04-18 15:00 UTC, beccadawson commented on package-lock.json
Please can you paste develop's lockfile over yours (or delete the file?) then run npm install (whilst on erbium)

2023-04-19 12:07 UTC, ryanfitton-ap commented on package-lock.json
@beccadawson Still no luck. I tried early version before 'erbium', which was 'v12.14.1', this seemed to install but Travis checks did not pass.

2023-04-20 14:22 UTC, ryanfitton-ap commented
@beccadawson @kimoshinowo98 Updated the readme with notes on the correct nvm and npm versions to use. 

The package.lock file has been updated too, with just one small change made when compared with the develop version.

2023-04-21 07:51 UTC, ryanfitton-ap commented
@beccadawson  Updated the package .json to use version 1.2.0 of the Stylelint Config.

But now seeing different errors in Travis: https://app.travis-ci.com/github/AgePartnership/oleg-starter-pack/builds/262475440

2023-04-21 08:27 UTC, ryanfitton-ap commented
@beccadawson  passing now, removed the git+ssh from the package dependency.

2023-04-21 13:40 UTC, kimoshinowo98 reviewed
Changes in package-lock now mostly look fine apart from:
- `node-releases` goes up by a major version
-  `yallist` and `lru-cache` are both going down by a major version

Worth installing this branch on the web.ap and mjolnir-templates repos and making sure Travis passes

2023-04-28 08:28 UTC, kimoshinowo98 approved these changes

2023-05-02 07:35 UTC, merged